#!/bin/sh
# DEBIAN_ISO_PROJECT/auto/config
# Configuração automática para gerar uma Live ISO Debian Trixie com ZFS

lb config noauto \
    --mode debian \
    --distribution trixie \
    --architectures amd64 \
    --archive-areas "main contrib non-free-firmware" \
    --linux-packages "linux-image linux-headers" \
    --mirror-binary "http://ftp.br.debian.org/debian/" \
    --mirror-chroot "http://ftp.br.debian.org/debian/" \
    --mirror-bootstrap "http://ftp.br.debian.org/debian/" \
    --bootappend-live "boot=live components hostname=debian-zfs-nas username=admin locales=pt_BR.UTF-8 keyboard-layouts=br timezone=America/Cuiaba" \
    "${@}"
